export const CATEGORIES = [
  { id: "paintings", label: "Paintings", count: 415 },
  { id: "sculptures", label: "Sculptures", count: 226 },
  { id: "ceramics", label: "Ceramics & Pottery", count: 138 },
  { id: "photography", label: "Photography", count: 190 },
  { id: "digital", label: "Digital & New Media", count: 84 },
  { id: "textile", label: "Textile & Fiber Art", count: 61 },
  { id: "printmaking", label: "Printmaking & Monotype", count: 42 },
];

export const MEDIUMS = [
  "Oil",
  "Acrylic",
  "Stoneware",
  "Bronze",
  "Linen",
  "Archival Ink",
  "Marble",
  "Porcelain",
  "Watercolor",
  "Charcoal",
  "Wood",
  "Glass",
];

export const ARTWORKS = [
  {
    id: 1,
    title: "Resonance in Sienna No. IV",
    artist: "Elena Voss",
    location: "Lyon, France",
    category: "paintings",
    medium: "Oil on Heavy Canvas",
    dims: "120 x 90 cm",
    value: 4200,
    img: "https://images.unsplash.com/photo-1541961017774-22349e4a1262?q=80&w=900&auto=format&fit=crop",
    tag: "Original Oil",
  },
  {
    id: 2,
    title: "Volcanic Tellic Amphora",
    artist: "Renzo Takahashi",
    location: "Kyoto, Japan",
    category: "ceramics",
    medium: "Stoneware & Ash Glaze",
    dims: "44 x 28 cm",
    value: 850,
    img: "https://images.unsplash.com/photo-1610701596007-11502861dcfa?q=80&w=900&auto=format&fit=crop",
    tag: "Wood-Fired Stoneware",
  },
  {
    id: 3,
    title: "Tectonic Equilibrium",
    artist: "Matteo Rinni",
    location: "Carrara, Italy",
    category: "sculptures",
    medium: "Hand-Carved Marble",
    dims: "60 x 38 x 30 cm",
    value: 7800,
    img: "https://images.unsplash.com/photo-1554188248-986adbb73be4?q=80&w=900&auto=format&fit=crop",
    tag: "Carved Travertine",
  },
  {
    id: 4,
    title: "Strata of Winter Breath",
    artist: "Astrid Lindgren",
    location: "Stockholm, Sweden",
    category: "textile",
    medium: "Woven Linen & Wool",
    dims: "140 x 85 cm",
    value: 1950,
    img: "https://images.unsplash.com/photo-1600166898405-da9535204843?q=80&w=900&auto=format&fit=crop",
    tag: "Textile Sculpture",
  },
  {
    id: 5,
    title: "Shadows of the Solstice",
    artist: "Mateo Morales",
    location: "Oaxaca, Mexico",
    category: "photography",
    medium: "Archival Pigment on Rag",
    dims: "64 x 45 cm",
    value: 680,
    img: "https://images.unsplash.com/photo-1519681393784-d120267933ba?q=80&w=900&auto=format&fit=crop",
    tag: "Limited Edition Print",
  },
  {
    id: 6,
    title: "Echoes in Ochre",
    artist: "Julian Cross",
    location: "London, UK",
    category: "paintings",
    medium: "Acrylic & Mineral Gesso",
    dims: "110 x 95 cm",
    value: 3100,
    img: "https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?q=80&w=900&auto=format&fit=crop",
    tag: "Mixed Media on Canvas",
  },
  {
    id: 7,
    title: "Quiet Basin, Study II",
    artist: "Noor Haddad",
    location: "Amman, Jordan",
    category: "ceramics",
    medium: "Porcelain & Slip",
    dims: "30 x 30 cm",
    value: 1120,
    img: "https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?q=80&w=900&auto=format&fit=crop",
    tag: "Thrown Porcelain",
  },
  {
    id: 8,
    title: "Fold, Unfold",
    artist: "Priya Nair",
    location: "Kochi, India",
    category: "sculptures",
    medium: "Cast Bronze",
    dims: "52 x 20 x 20 cm",
    value: 5400,
    img: "https://images.unsplash.com/photo-1544967082-d9d25d867d66?q=80&w=900&auto=format&fit=crop",
    tag: "Limited Cast, 3 of 9",
  },
  {
    id: 9,
    title: "Signal Garden",
    artist: "Theo Baptiste",
    location: "Montreal, Canada",
    category: "digital",
    medium: "Generative Print on Archival Paper",
    dims: "80 x 80 cm",
    value: 2250,
    img: "https://images.unsplash.com/photo-1620121692029-d088224ddc74?q=80&w=900&auto=format&fit=crop",
    tag: "Digital / New Media",
  },
  {
    id: 10,
    title: "Marigold Hour",
    artist: "Ananya Deshpande",
    location: "Jaipur, India",
    category: "paintings",
    medium: "Watercolor on Cotton Paper",
    dims: "56 x 76 cm",
    value: 980,
    img: "https://images.unsplash.com/photo-1578926288207-a90a5366759d?q=80&w=900&auto=format&fit=crop",
    tag: "Original Watercolor",
  },
  {
    id: 11,
    title: "Ashen Coastline",
    artist: "Bjorn Halvorsen",
    location: "Bergen, Norway",
    category: "photography",
    medium: "Silver Gelatin Print",
    dims: "50 x 60 cm",
    value: 1450,
    img: "https://images.unsplash.com/photo-1500534623283-312aade485b7?q=80&w=900&auto=format&fit=crop",
    tag: "Fine Art Black & White",
  },
  {
    id: 12,
    title: "Vessel of Small Mercies",
    artist: "Renzo Takahashi",
    location: "Kyoto, Japan",
    category: "ceramics",
    medium: "Raku Stoneware",
    dims: "24 x 24 cm",
    value: 620,
    img: "https://images.unsplash.com/photo-1493106819501-66d381c466f1?q=80&w=900&auto=format&fit=crop",
    tag: "Raku Fired",
  },
  {
    id: 13,
    title: "Woven Meridian",
    artist: "Astrid Lindgren",
    location: "Stockholm, Sweden",
    category: "textile",
    medium: "Hand-Knotted Wool Tapestry",
    dims: "180 x 120 cm",
    value: 3400,
    img: "https://images.unsplash.com/photo-1615529162924-f8605388461d?q=80&w=900&auto=format&fit=crop",
    tag: "Tapestry",
  },
  {
    id: 14,
    title: "Fault Lines, Study I",
    artist: "Matteo Rinni",
    location: "Carrara, Italy",
    category: "sculptures",
    medium: "Bronze on Granite Base",
    dims: "40 x 22 x 18 cm",
    value: 4650,
    img: "https://images.unsplash.com/photo-1577083552431-6e5fd01aa342?q=80&w=900&auto=format&fit=crop",
    tag: "Limited Cast, 5 of 12",
  },
  {
    id: 15,
    title: "Monsoon Interior",
    artist: "Priya Nair",
    location: "Kochi, India",
    category: "paintings",
    medium: "Charcoal & Ink on Paper",
    dims: "70 x 100 cm",
    value: 1580,
    img: "https://images.unsplash.com/photo-1549289524-06cf8837ace5?q=80&w=900&auto=format&fit=crop",
    tag: "Charcoal Drawing",
  },
  {
    id: 16,
    title: "Latticework No. 7",
    artist: "Theo Baptiste",
    location: "Montreal, Canada",
    category: "digital",
    medium: "Algorithmic Light Installation Print",
    dims: "90 x 60 cm",
    value: 2900,
    img: "https://images.unsplash.com/photo-1633186710895-309db2eca9e4?q=80&w=900&auto=format&fit=crop",
    tag: "Digital / New Media",
  },
  {
    id: 17,
    title: "Blown Horizon Vessel",
    artist: "Noor Haddad",
    location: "Amman, Jordan",
    category: "sculptures",
    medium: "Hand-Blown Glass",
    dims: "35 x 18 cm",
    value: 1780,
    img: "https://images.unsplash.com/photo-1528732515498-6237514eeaa4?q=80&w=900&auto=format&fit=crop",
    tag: "Hand-Blown Glass",
  },
  {
    id: 18,
    title: "Relief in Walnut",
    artist: "Bjorn Halvorsen",
    location: "Bergen, Norway",
    category: "sculptures",
    medium: "Carved Walnut Wood",
    dims: "48 x 32 x 10 cm",
    value: 2350,
    img: "https://images.unsplash.com/photo-1567696911980-2eed69a46042?q=80&w=900&auto=format&fit=crop",
    tag: "Carved Wood Relief",
  },
  {
    id: 19,
    title: "Riverbed Monotype III",
    artist: "Ananya Deshpande",
    location: "Jaipur, India",
    category: "printmaking",
    medium: "Monotype on Rag Paper",
    dims: "38 x 50 cm",
    value: 540,
    img: "https://images.unsplash.com/photo-1578301978018-3005759f48f7?q=80&w=900&auto=format&fit=crop",
    tag: "Monotype Print",
  },
  {
    id: 20,
    title: "Threadbare Constellations",
    artist: "Julian Cross",
    location: "London, UK",
    category: "textile",
    medium: "Embroidery on Linen",
    dims: "60 x 60 cm",
    value: 1290,
    img: "https://images.unsplash.com/photo-1520222984843-df35ebc0f24d?q=80&w=900&auto=format&fit=crop",
    tag: "Hand Embroidery",
  },
];